
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: observatoria.observatorium.observatorium
spec:
  group: observatorium.observatorium
  names:
    kind: Observatorium
    listKind: ObservatoriumList
    plural: observatoria
    singular: observatorium
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Observatorium is the Schema for the observatoria API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ObservatoriumSpec defines the desired state of Observatorium
          properties:
            thanos:
              description: Thanos Spec
              properties:
                compactorReplicas:
                  description: Number of instances to deploy for a Thanos Compactor.
                  format: int32
                  type: integer
                compactorResources:
                  description: Resources for Compactor pods
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                image:
                  description: Thanos Image name
                  type: string
                objectStoreConfigSecret:
                  description: Object Store Config Secret for Thanos
                  type: string
                querierReplicas:
                  description: Number of instances to deploy for a Thanos querier.
                  format: int32
                  type: integer
                querierResources:
                  description: Resources for Querier pods
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                receivePvcSize:
                  description: Receive PVC size
                  type: string
                receiveReplicas:
                  description: Number of instances to deploy for a Thanos Receive.
                  format: int32
                  type: integer
                receiveResources:
                  description: Resources for Receive pods
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                receiveStorageClass:
                  description: Receive Storage Class
                  type: string
                storeReplicas:
                  description: Number of instances to deploy for a Thanos Store.
                  format: int32
                  type: integer
                storeResources:
                  description: Resources for Store pods
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                tag:
                  description: Tag of Thanos sidecar container image to be deployed.
                  type: string
                thanosReceiveControllerSpec:
                  properties:
                    hashrings:
                      description: Hashrings describes a list of Hashrings
                      items:
                        properties:
                          name:
                            description: Thanos Hashring name
                            type: string
                          tenants:
                            description: Tenants describes a lists of tenants.
                            items:
                              type: string
                            type: array
                        required:
                        - name
                        type: object
                      type: array
                    image:
                      description: Thanos receive controller Image name
                      type: string
                    tag:
                      description: Tag describes the tag of Thanos receive controller
                        to use.
                      type: string
                  required:
                  - image
                  type: object
              required:
              - image
              - objectStoreConfigSecret
              - receivePvcSize
              - receiveStorageClass
              - tag
              - thanosReceiveControllerSpec
              type: object
          required:
          - thanos
          type: object
        status:
          description: ObservatoriumStatus defines the observed state of Observatorium
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
